name: Autopep8

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install autopep8

      - name: Run Autopep8
        run: |
          autopep8 --in-place --aggressive --aggressive hw2/hw2_debugging.py
          autopep8 --in-place --aggressive --aggressive hw2/rand.py

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Setup Git Authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.SE_HW2 }}@github.com/${{ github.repository }}.git

      - name: Fetch Latest Changes
        run: git fetch origin

      - name: Rebase Latest Changes
        run: |
          git rebase origin/main || {
            echo "failed.";
            exit 1;
          }

      - name: Check for Changes
        id: check-changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "::set-output name=changes::false"
          else
            echo "::set-output name=changes::true"
          fi

      - name: Commit and Push Changes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git commit -m "Update python files with latest Autopep8 results"
          git push origin HEAD:main
