name: Pylint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Create traces directory
        run: |
          mkdir -p traces

      - name: Run Pylint and Replace Output
        run: |
          pylint hw2/hw2_debugging.py hw2/rand.py > traces/pylint_trace.txt || true
          if [ -f post_traces/pylint_trace.txt ]; then
            cat pylint.txt >> post_traces/pylint_trace.txt
          else
            mv pylint.txt post_traces/pylint_trace.txt
          fi

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Setup Git Authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.SE_HW2 }}@github.com/${{ github.repository }}.git

      - name: Commit and Push Changes
        run: |
          git add traces/pylint_trace.txt
          git commit -m "Update pylint_traces.txt with latest Pylint results"
          git push origin HEAD:main
