name: Pylint File

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Create traces directory
        run: |
          mkdir -p traces

      - name: Run Pylint and Replace Output
        run: |
          pylint hw2/hw2_debugging.py hw2/rand.py > traces/pylint_trace.txt

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add traces/pylint_trace.txt
          git commit -m "Update pylint_trace.txt with latest Pylint results"
          git push origin main
